const ACTION_TYPES = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",

  /* 4. */
  ADD_TASK_REQUESTED: "ADD_TASK_REQUESTED",
  ADD_TASK_SUCCESSED: "ADD_TASK_SUCCESSED",
  ADD_TASK_ERROR: "ADD_TASK_ERROR",

  DELETE_TASK: "DELETE_TASK",
};

export default ACTION_TYPES;
